### ISSUE TITLE
1.20.4 Support

### ISSUE THREAD

**Issue by Dynamic-Gravity** [Imprex-Development/zero-inventory-problems#14]
### Description

Upon upgrading from 1.20.2 -> 1.20.4 ZIP appears to not be compatible and throws error messages to STDERR.

### Reproduction Steps

Latest stable version of Minecraft with the latest stable version of ZIP.

### Expected Behaviour

The plugin to work with  *Server version: v1_20_R3 - 1.20.4*

### Server Details

Current: git-Purpur-2110 (MC: 1.20.4)

### Zero Inventory Problems Version

1.0.4

### Logs and Configs

```
[12:19:04] [Server thread/INFO]: [ZeroInventoryProblems] Enabling ZeroInventoryProblems v1.0.4
[12:19:04] [Server thread/ERROR]: [bukkit.zeroinventoryproblems] [ZeroInventoryProblems] An error occured while enabling plugin
java.lang.RuntimeException: Server version "v1_20_R3" is currently not supported!
        at net.imprex.zip.NmsInstance.initialize(NmsInstance.java:33) ~[zip-plugin-1.0.4.jar:?]
        at net.imprex.zip.BackpackPlugin.onEnable(BackpackPlugin.java:47) ~[zip-plugin-1.0.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2110]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.imprex.zip.nms.v1_20_R3.ZipNmsManager
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at net.imprex.zip.NmsInstance.initialize(NmsInstance.java:29) ~[zip-plugin-1.0.4.jar:?]
        ... 13 more
```

**Comment by Dynamic-Gravity** [comment]
I just updated to the 1.0.6 release and when ever someone tries to interact with anything they see the following message printed to chat.

I turned on debug mode but do not see anything in the server console.

![image](https://github.com/Imprex-Development/zero-inventory-problems/assets/22669809/97e2075b-82b8-4fae-8d89-79e3a9b9f794)

**Comment by NgLoader** [comment]
Are there any console errors?
Can you try the 1.0.5 version please

**Comment by NgLoader** [comment]
> I just updated to the 1.0.6 release and when ever someone tries to interact with anything they see the following message printed to chat.
> 
> I turned on debug mode but do not see anything in the server console.
> 
> ![image](https://private-user-images.githubusercontent.com/22669809/293306381-97e2075b-82b8-4fae-8d89-79e3a9b9f794.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTgzMDksIm5iZiI6MTcwMzg1ODAwOSwicGF0aCI6Ii8yMjY2OTgwOS8yOTMzMDYzODEtOTdlMjA3NWItODJiOC00ZmFlLThkODktNzllM2E5YjlmNzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEzNTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYmI0YmQxYjBiNmY2MzZiMGIwYmFkMTczMzQ0MmJlYTQ1MmJkZWFlOThjNWY0ZGQ4ZjA2ZGJhOTA3MmVhNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7uRDAYVC9toAMt1SozvhdK8RJnVzGPozCEr5vcecCFM)
> 
> I apologize for the blurriness I had to be quick.

Should be fixed in version 1.0.7

**Comment by Dynamic-Gravity** [comment]
`v1.0.7` seems to work for me.

I can use the backpack, and I am not presented with the above "backpack cant be loaded" error when right clicking on anything else.

I see a warning in the server console, but it doesn't appear to affect anything.

```
minecraft@minecraft:~/bin/server/plugins$ grep ZeroInventoryProblems ../logs/latest.log 
[10:32:57] [Server thread/INFO]: [ZeroInventoryProblems] Loading server plugin ZeroInventoryProblems v1.0.7
[10:33:33] [Server thread/INFO]: [ZeroInventoryProblems] Enabling ZeroInventoryProblems v1.0.7
[10:33:33] [Server thread/WARN]: [bukkit.zeroinventoryproblems] [ZeroInventoryProblems] Unable to find a message key for "unableToLoadBackpack" in language file "en_US"
```

**Comment by NgLoader** [comment]
> `v1.0.7` seems to work for me.
> 
> I can use the backpack, and I am not presented with the above "backpack cant be loaded" error when right clicking on anything else.
> 
> I see a warning in the server console, but it doesn't appear to affect anything.
> 
> ```
> minecraft@minecraft:~/bin/server/plugins$ grep ZeroInventoryProblems ../logs/latest.log 
> [10:32:57] [Server thread/INFO]: [ZeroInventoryProblems] Loading server plugin ZeroInventoryProblems v1.0.7
> [10:33:33] [Server thread/INFO]: [ZeroInventoryProblems] Enabling ZeroInventoryProblems v1.0.7
> [10:33:33] [Server thread/WARN]: [bukkit.zeroinventoryproblems] [ZeroInventoryProblems] Unable to find a message key for "unableToLoadBackpack" in language file "en_US"
> ```

Yes, everything should work fine now

**Comment by Dynamic-Gravity** [comment]
Thank you very much :)
