### ISSUE TITLE
Problem warnig

### ISSUE THREAD

**Issue by Peppe-73** [Imprex-Development/zero-inventory-problems#33]
### Description

I just updated to Paper 81 and got these warnings in the console

[12:04:51 WARN]: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.inventory.CraftMetaSkull.setProfile(com.mojang.authlib.GameProfile) [12:04:51 WARN]: at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848) [12:04:51 WARN]: at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredMethod(AbstractDefaultRulesReflectionProxy.java:95) [12:04:51 WARN]: at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredMethod(Unknown Source) [12:04:51 WARN]: at zip-plugin-1.0.14.jar//net.imprex.zip.common.ReflectionUtil.getMethod(ReflectionUtil.java:98) [12:04:51 WARN]: at zip-plugin-1.0.14.jar//net.imprex.zip.nms.v1_21_R1.ZipNmsManager.<clinit>(ZipNmsManager.java:32) [12:04:51 WARN]: at java.base/java.lang.Class.forName0(Native Method) [12:04:51 WARN]: at java.base/java.lang.Class.forName(Class.java:534) [12:04:51 WARN]: at java.base/java.lang.Class.forName(Class.java:513) [12:04:51 WARN]: at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) [12:04:51 WARN]: at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) [12:04:51 WARN]: at zip-plugin-1.0.14.jar//net.imprex.zip.NmsInstance.initialize(NmsInstance.java:29) [12:04:51 WARN]: at zip-plugin-1.0.14.jar//net.imprex.zip.BackpackPlugin.onEnable(BackpackPlugin.java:47) [12:04:51 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) [12:04:51 WARN]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) [12:04:51 WARN]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) [12:04:51 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) [12:04:51 WARN]: at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) [12:04:51 WARN]: at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) [12:04:51 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) [12:04:51 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) [12:04:51 WARN]: at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) [12:04:51 WARN]: at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) [12:04:51 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) [12:04:51 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583) [12:04:51 ERROR]: [bukkit.zeroinventoryproblems] [ZeroInventoryProblems] An error occured while enabling plugin java.lang.ClassCastException: Error by setting skull profile at zip-plugin-1.0.14.jar/net.imprex.zip.nms.v1_21_R1.ZipNmsManager.setSkullProfile(ZipNmsManager.java:108) ~[zip-plugin-1.0.14.jar:?] at zip-plugin-1.0.14.jar/net.imprex.zip.NmsInstance.setSkullProfile(NmsInstance.java:50) ~[zip-plugin-1.0.14.jar:?] at zip-plugin-1.0.14.jar/net.imprex.zip.util.ItemFactory.setSkullProfile(ItemFactory.java:78) ~[zip-plugin-1.0.14.jar:?] at zip-plugin-1.0.14.jar/net.imprex.zip.BackpackType.<init>(BackpackType.java:25) ~[zip-plugin-1.0.14.jar:?] at zip-plugin-1.0.14.jar/net.imprex.zip.BackpackRegistry.register(BackpackRegistry.java:35) ~[zip-plugin-1.0.14.jar:?] at zip-plugin-1.0.14.jar/net.imprex.zip.BackpackPlugin.onEnable(BackpackPlugin.java:51) ~[zip-plugin-1.0.14.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-81-13a2395] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-81-13a2395] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-81-13a2395] at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-81-13a2395] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-81-13a2395] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-81-13a2395] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-81-13a2395] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-81-13a2395] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-81-13a2395] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Reproduction Steps

I just updated to Paper 81 and got these warnings in the console

### Expected Behaviour

I just updated to Paper 81 and got these warnings in the console

### Server Details

Paper 81 MC 1.21.1

### Zero Inventory Problems Version

1.0.14

**Comment by Peppe-73** [comment]
When will an update be available that fixes this problem?

**Comment by NgLoader** [comment]
Tomorrow hopefully

**Comment by Peppe-73** [comment]
Please update

**Comment by NgLoader** [comment]
Hey, sry for the delay this issue shout be fixed in version ``1.0.15``

**Comment by NgLoader** [comment]
Hey, sry for the delay this issue shout be fixed in version 1.0.15
